apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: queue

resources:
  - ../../base
  - poddisruptionbudget.yaml

patches:
  - target:
      kind: Deployment
      name: worker-etl
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"
      - op: add
        path: /spec/template/spec/topologySpreadConstraints
        value:
          - maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: worker-etl
  - target:
      kind: ConfigMap
      name: worker-etl-env
    patch: |
      - op: replace
        path: /data/ETL_PREFETCH_COUNT
        value: "5"

images:
  - name: quay.io/opl/worker-etl
    newTag: latest
