apiVersion: apps/v1
kind: Deployment
metadata:
  name: opl-email-service
spec:
  template:
    spec:
      containers:
      - name: email-service
        image: quay.io/dcurran/opl-email-service:latest