apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opl-email-service

bases:
  - ../../base

resources:
  - namespace.yaml

# Patch configmap to use correct namespace for Mailhog SMTP
patchesStrategicMerge:
  - configmap-patch.yaml
  - deployment-patch.yaml