apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml

commonLabels:
  app: opl-email-service
  app.kubernetes.io/name: opl-email-service
  app.kubernetes.io/component: email
  app.kubernetes.io/part-of: openshift-partner-labs
  app.kubernetes.io/managed-by: kustomize
