apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opl-dev

resources:
  - ../../base

nameSuffix: ""

patches:
  - target:
      kind: Deployment
      name: worker-etl
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "32Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "128Mi"

configMapGenerator:
  - name: worker-etl-env
    behavior: merge
    literals:
      - ETL_RABBITMQ_HOST=rabbitmq.opl-dev.svc.cluster.local

images:
  - name: quay.io/opl/worker-etl
    newTag: dev
