apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: queue

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secrets.yaml
  - configmap-env.yaml
  - configmap-etl-schema.yaml
  - deployment.yaml
