apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opl-system

commonLabels:
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - configmap-env.yaml
  - ../../configmap-etl-schema.yaml
  - networkpolicy.yaml
  - deployment.yaml
