apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-etl
  namespace: queue
  labels:
    app.kubernetes.io/name: worker-etl
    app.kubernetes.io/component: etl
    app.kubernetes.io/part-of: openshift-partner-labs
